export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "categor/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "categor/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "categor/FETCH_CATEGORIES_FAILED",
};
